name = "WIGXJPFjl"
uuid = "c012394e-041f-4dac-954c-af2908646be0"
authors = ["wes <jhwesterfield@ucdavis.edu>"]
repo = "https://github.com/wes648/WIGXJPFjl.jl"
version = "0.1.1"

[compat]
julia = "^1.10.1"
