name = "WIGXJPFjl"
uuid = "c012394e-041f-4dac-954c-af2908646be0"
authors = ["wes <jhwesterfield@ucdavis.edu>"]
version = "0.1.1"
repo = "https://github.com/wes648/WIGXJPFjl.jl"

[deps]
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
julia = "^1.9"
BufferedStreams = "^1.2.1"
CodecZlib = "^0.7.3"
HTTP = "^1.10.0"
Tar = "^1.10.0"

